version: 1
jobs:
  build:
    filters:
      branches:
        only: master
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: tadone.github.io
      - GH_NAME: "Tad Swider"
      - GH_EMAIL: "tadone@gmail.com"
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn global add vuepress
      - run: sh ./docs/deploy.sh
